name: Hello World

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: ls code
      run: ls -lhtra

    - name: Print Hello World
      run: echo "Hello, World!"
